### ISSUE TITLE
Axis Error

### ISSUE THREAD

**Issue by raksha-agarwal** [sbettid/GPSClean#1]
Hi
Was trying to use the cleaning application but I am getting the following error:

 ____  ____   ____    ____  _                     
 / ___||  _ \ / ___|  / ___|| |  ___   __ _  _ __  
| |  _ | |_) |\___ \ | |    | | / _ \ / _` || '_ \ 
| |_| ||  __/  ___) || |___ | ||  __/| (_| || | | |
 \____||_|    |____/  \____||_| \___| \__,_||_| |_|
                                                   

Version:  1.0.0 

Reading your trace...
Loading the model...
Predicting points...
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
Traceback (most recent call last):
  File "/disk1/raksha/GPSClean/raksha-clean-env/bin/gpsclean", line 8, in <module>
    sys.exit(main())
  File "/disk1/raksha/GPSClean/raksha-clean-env/lib/python3.9/site-packages/gpsclean/gpsclean.py", line 77, in main
    segments, indices, predictions = ft.predict_trace(interpreter, deltas, 15, 2)
  File "/disk1/raksha/GPSClean/raksha-clean-env/lib/python3.9/site-packages/gpsclean/FullTraining.py", line 114, in predict_trace
    predictions=np.argmax(predicted_segments,axis=2)
  File "<__array_function__ internals>", line 180, in argmax
  File "/disk1/raksha/GPSClean/raksha-clean-env/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 1216, in argmax
    return _wrapfunc(a, 'argmax', axis=axis, out=out, **kwds)
  File "/disk1/raksha/GPSClean/raksha-clean-env/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 54, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "/disk1/raksha/GPSClean/raksha-clean-env/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 43, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
numpy.AxisError: axis 2 is out of bounds for array of dimension 1

Attaching the sample gpx file
https://drive.google.com/file/d/1yNoTzNmDQM5jwPiSksnbVg52ssLKaw-X/view?usp=sharing

**Comment by sbettid** [comment]
Hi! Thank you for reporting this, let me investigate it and I will inform you as soon as possible.

**Comment by sbettid** [comment]
HI @raksha-agarwal ! I investigate a bit your issue and found it resides in the fact that the GPX trace does not contain any track but only waypoints, while the package expects at least a GPX track... And yes, for sure the exception is not good and the validation should check that and provide an useful message. I promise I will implement it in a couple of days. 

In any case, it is possible to convert a trace made of only waypoints in a standard track by using, for example, https://www.gpsbabel.org/. Using the following command I was able to convert the trace and apply the cleaning procedure: 

`gpsbabel -i gpx -f sample.gpx -x transform,trk=wpt -o gpx -F track2.gpx`

I attach the converted track and the result of the cleaning procedure in a zip folder. Please let me know if I can help you an futher or if we can consider the issue close. Thank you!

[sample.zip](https://github.com/sbettid/GPSClean/files/9625224/sample.zip)

**Comment by raksha-agarwal** [comment]
Hi @sbettid 
Thank you for the help. It is working now.
You may consider the issue to be closed.
Regards
